export const user = [
  {
    username: 'colincruz',
    password: 1491,
    current_plan: {
      name: 'default',
      difficulty: 'default',
      date_started: '',
      exercises: [{
        day:1,
        name:''
      }],
      dishes: [{}],
    },
    progress: {
      day: 29,
      height: 172,
      weight: 67,
      heartrate: 0,
      target_weight: 60,
      target_heartrate: 0,
      progress_weight: [67, 67, 66, 64],
      progress_heartrate: [],
    },
    settings: {
      sync_email: 'colin.cruz@gmail.com',
      show_sync: true,
      notification: false,
      sound: false,
      sync: false,
    },
  },
  {
    username: 'jolofelix',
    password: 'pogi69',
    height: 178,
    weight: 75,
    progress: [75, 74, 73.4],
  },
  {
    username: 'tadokazaki',
    password: 'ballislife',
    height: 165,
    weight: 68,
    progress: [67.5, 66, 64.7],
  },
  {
    username: 'ajcarreon',
    password: 'pepsicola123',
    height: 175.2,
    weight: 65.7,
    progress: [65, 65, 64.2],
  },
  {
    username: 'aaronsiwa',
    password: 'elitebadboy',
    height: 172,
    weight: 82,
    progress: [81, 80, 78.5],
  },
  {
    username: 'karlofang',
    password: 'ruth10',
    height: 172,
    weight: 65.7,
    progress: [65.7, 64.2, 62.4],
  },
  {
    username: 'jumibrolaza',
    password: 'may181991',
    height: 172,
    weight: 68,
    progress: [68, 67, 67],
  },
  {
    username: 'cedricsantos',
    password: 'totoybrown69',
    height: 177.8,
    weight: 75,
    progress: [75, 74.6, 73],
  },
  {
    username: 'nichaelsantos',
    password: 'nenenggata',
    height: 165,
    weight: 54,
    progress: [53, 52.4, 51],
  },
  {
    username: 'paolorioflorido',
    password: 'monti',
    height: 165,
    weight: 76.2,
    progress: [76, 75, 74.5],
  },
]
