const imageLoader = {
  Discover: require('../images/optimized/science.jpg'),
  Eat: require('../images/optimized/food.jpg'),
  Heart: require('../images/heart.png'),
  Plans: require('../images/optimized/jog.jpg'),
  Progress: require('../images/optimized/stats.jpg'),
  Reference: require('../images/optimized/science.jpg'),
  Splash: require('../images/splash.jpg'),
  Workout: require('../images/optimized/curls.jpg'),
  Wallpaper: require('../images/optimized/bg.jpg'),
  Heart: require('../images/heart.png'),
  'bicycle crunches': require('../images/exercises/bicycle crunches.jpg'),
  'body rocks': require('../images/exercises/body rocks.jpg'),
  'burpees': require('../images/exercises/burpees.jpg'),
  'butt kick': require('../images/exercises/butt kick.jpg'),
  'calf raises': require('../images/exercises/calf raises.png'),
  'chair pose': require('../images/exercises/chair pose.png'),
  'close push ups': require('../images/exercises/close push ups.jpg'),
  'crab walk': require('../images/exercises/crab walk.jpg'),
  'crunches': require('../images/exercises/crunches.jpg'),
  'diamond push ups': require('../images/exercises/diamond push ups.jpg'),
  'double leg lift': require('../images/exercises/double leg lift.png'),
  'extended plank': require('../images/exercises/extended plank.jpg'),
  'flutter kick': require('../images/exercises/flutter kick.jpg'),
  'frog jump': require('../images/exercises/frog jump.jpg'),
  'frozen v sit': require('../images/exercises/frozen v sit.jpg'),
  'high knee': require('../images/exercises/high knee.jpg'),
  'jog': require('../images/exercises/jog.jpg'),
  'jumping jacks': require('../images/exercises/jumping jacks.jpg'),
  'leg raises': require('../images/exercises/leg raises.jpg'),
  'lunges': require('../images/exercises/lunges.jpg'),
  'lying hip raises': require('../images/exercises/lying hip raises.jpg'),
  'mountain climbers': require('../images/exercises/mountain climbers.jpg'),
  'plank': require('../images/exercises/plank.jpg'),
  'plie squats': require('../images/exercises/plie squats.jpg'),
  'push ups': require('../images/exercises/push ups.jpg'),
  'side lunges': require('../images/exercises/side lunges.jpg'),
  'sit ups': require('../images/exercises/sit ups.jpg'),
  'spinal balance': require('../images/exercises/spinal balance.jpg'),
  'squat jumps': require('../images/exercises/squat jumps.jpg'),
  'squats': require('../images/exercises/squats.jpg'),
  'stationary jog': require('../images/exercises/stationary jog.jpg'),
  'superman': require('../images/exercises/superman.jpg'),
  'switch kick': require('../images/exercises/switch kick.jpg'),
  'tricep push ups': require('../images/exercises/tricep push ups.jpg'),
  'tuck jump': require('../images/exercises/tuck jump.jpg'),
  'v ups': require('../images/exercises/v ups.jpg'),
  'wall sit': require('../images/exercises/wall sit.jpg'),
  'wide arm push ups': require('../images/exercises/wide arm push ups.png'),
};
export default imageLoader;
