const imageLoader = {
  Discover: require('../images/optimized/science.jpg'),
  Eat: require('../images/optimized/food.jpg'),
  Heart: require('../images/heart.png'),
  Plans: require('../images/optimized/jog.jpg'),
  Progress: require('../images/optimized/stats.jpg'),
  Reference: require('../images/optimized/science.jpg'),
  Splash: require('../images/splash.jpg'),
  Workout: require('../images/optimized/curls.jpg'),
  Wallpaper: require('../images/optimized/bg.jpg'),
  Heart: require('../images/heart.png'),
  'bicycle crunches': require('../images/exercises/bicycle_crunches.jpg'),
  'body rocks': require('../images/exercises/body_rocks.jpg'),
  'burpees': require('../images/exercises/burpees.jpg'),
  'butt kick': require('../images/exercises/butt_kick.jpg'),
  'calf raises': require('../images/exercises/calf_raise.png'),
  'chair pose': require('../images/exercises/chair_pose.png'),
  'close push ups': require('../images/exercises/close_push_ups.jpg'),
  'crab walk': require('../images/exercises/crab_walk.jpg'),
  'crunches': require('../images/exercises/crunches.jpg'),
  'diamond push ups': require('../images/exercises/diamond_push_ups.jpg'),
  'double leg lift': require('../images/exercises/double_leg_lift.png'),
  'extended plank': require('../images/exercises/extended_plank.jpg'),
  'flutter kick': require('../images/exercises/flutter_kick.jpg'),
  'frog jump': require('../images/exercises/frog_jump.jpg'),
  'frozen v sit': require('../images/exercises/frozen_v_sit.jpg'),
  'high knee': require('../images/exercises/high_knee.jpg'),
  'jog': require('../images/exercises/jog.jpg'),
  'jumping jacks': require('../images/exercises/jumping_jacks.jpg'),
  'leg raises': require('../images/exercises/leg_raises.jpg'),
  'lunges': require('../images/exercises/lunges.jpg'),
  'lying hip raises': require('../images/exercises/lying_hip_raises.jpg'),
  'mountain climbers': require('../images/exercises/mountain_climbers.jpg'),
  'plank': require('../images/exercises/plank.jpg'),
  'plie squats': require('../images/exercises/plie_squats.jpg'),
  'push ups': require("../images/exercises/push_ups.jpg"),
  'side lunges': require('../images/exercises/side_lunges.jpg'),
  'sit ups': require('../images/exercises/sit_ups.jpg'),
  'spinal balance': require('../images/exercises/spinal_balance.jpg'),
  'squat jumps': require('../images/exercises/squat_jumps.jpg'),
  'squats': require('../images/exercises/squats.jpg'),
  'stationary jog': require('../images/exercises/stationary_jog.jpg'),
  'superman': require('../images/exercises/superman.jpg'),
  'switch kick': require('../images/exercises/switch_kick.jpg'),
  'tricep push ups': require('../images/exercises/tricep_push_ups.jpg'),
  'tuck jump': require('../images/exercises/tuck_jump.jpg'),
  'v ups': require('../images/exercises/v_ups.jpg'),
  'wall sit': require('../images/exercises/wall_sit.jpg'),
  'wide arm push ups': require('../images/exercises/wide_arm_push_ups.png'),
};
export default imageLoader;
